### ISSUE TITLE
Access to data from Estonia

### ISSUE THREAD

**Issue by peterdesmet** [enram/dmp#10]
@leijnse @adokter we are getting vp data from the two Estonian radars `eehar` and `eesyr`: http://enram.github.io/data-repository/?prefix=ee

However, Estonia is not listed as a signee in the OPERA/ENRAM license agreement. Are they willing to sign or should we remove that data?

**Comment by CeciliaNilsson709** [comment]
Estonia is included in the new license agreement

**Comment by peterdesmet** [comment]
Awesome! 👏 Any other new signees? In the 2016 agreement I have:

```
Austria
Belgium
Croatia
Czech Republic
Denmark
Finland
France
Germany
Netherlands
Norway
Poland
Portugal
Slovenia
Slovak Republic
Spain
Sweden
Switzerland
UK
```

**Comment by CeciliaNilsson709** [comment]
I sent you the draft of the agreement, it's not all signed and done yet

**Comment by peterdesmet** [comment]
Thanks. 👌 Seems Estonia is the only new member. Closing this issue.
